### ISSUE TITLE
Installing into GameData should allow choice of a subfolder

### ISSUE THREAD

**Issue by mheguy** [KSP-CKAN/metadata-webtool#13]
Currently when installing into GameData we don't allow a subfolder to be specified.

**Comment by janbrohl** [comment]
Added this in #12, I think. If not - please give an example install directive.

**Comment by janbrohl** [comment]
OK?

**Comment by mheguy** [comment]
`file:GameData/Mod/ModCore`, `install_to:GameData/Mod`

**Comment by janbrohl** [comment]
Subdirectories are allowed everywhere?

It seems that https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#install is not clear enough - at least for me. Opened issue KSP-CKAN/CKAN/issues/1770
