### ISSUE TITLE
Set spec_version to minimal required 

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/metadata-webtool#17]
`spec_version` is currently set to most current spec version (actually at the time of writing to a future version).

It should be set to the minimal version required to parse it correctly.

**Comment by janbrohl** [comment]
Small step in #18

**Comment by plague006** [comment]
I'd much rather see it set to `v1.2` as a default and in the event of someone using `Unlicense` the Jenkins test will reveal the error. I also think we shouldn't let submitters modify the field by hand at all as I've seen many people mistake `spec_version` for `version`.

**Comment by janbrohl** [comment]
Big step in #21
