### ISSUE TITLE
Expanding sections should collapse if clicked on again.

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/metadata-webtool#29]
I'm not sure there's a good justification for only allowing one section to be open, either. May want to be able to compare or copy/paste information across different sections.

**Comment by janbrohl** [comment]
Currently using default behavior of JQueryUI - i'll look into this

**Comment by janbrohl** [comment]
There is no option ( see https://api.jqueryui.com/accordion/ if you like ) to have several options open at once but being able to have all of them closed at once is just a config flag away - but why?

**Comment by politas** [comment]
If a user clicks on a tab and finds it has nothing they want to use, they should be able to close it.
