### ISSUE TITLE
Version compatibility should be more layman-friendly

### ISSUE THREAD

**Issue by mheguy** [KSP-CKAN/metadata-webtool#3]
Currently we have:

> examples: ==1.0 or <=1.1>=1.0.3

It might be best to present either the option of a specific ksp_version or setting the range (min and max). I think what we're asking is kind of unclear. Would we reject `1.1.2` because it has to be `==1.1.2`?

**Comment by janbrohl** [comment]
I made this so to be consistent with mod references where i use the same system.

i thought about it when implementing and no - in v0.1 just `1.1.2` is OK even though it is an undocumented feature.

**Comment by mheguy** [comment]
Oki.
