### ISSUE TITLE
Allow "any" as a ksp_version setting

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/metadata-webtool#30]
Though it would be good to request a justification when that is chosen, such as "flagmod", "agencymod"

**Comment by janbrohl** [comment]
There just needs to be a comment added stating actual behavior: Leaving that field empty will omit ksp_version from output which is equivalent to setting it to "any".

Also "any" should already be allowed as input for that field, too.

**Comment by politas** [comment]
It was popping up a warning message. 
And yes, leaving ksp_version out makes the client treat it as "any", but it's better to have it explicitly stated to indicate that it is a decision that has been made, rather than something that's been forgotten.
