### ISSUE TITLE
[Feature] Tags

### ISSUE THREAD

**Issue by Qazerowl** [KSP-CKAN/metadata-webtool#43]
I love the tags feature in CKAN. The metadata Webtool does not allow for adding tags. Adding a section for tags would be convenient.

I would not let users type custom tags, instead a list of checkboxes based on this page: https://github.com/KSP-CKAN/CKAN/wiki/Suggested-Tags ?

**Comment by HebaruSan** [comment]
This is a good suggestion, and I like the idea of checkboxes for the UI.

Ideally the sync with the wiki would be accomplished by reading from a formalized list somewhere, so we don't have to remember to update this tool when a new tag is added. Maybe it's time to add the tag list to the schema?
