### ISSUE TITLE
[Bug] Not all autofilled fields have a green background

### ISSUE THREAD

**Issue by DeltaDizzy** [KSP-CKAN/metadata-webtool#47]
![](https://media.discordapp.net/attachments/601456737203126281/1147336607893037227/image.png?width=1897&height=768)

When using GitHub as the source (though it possibly exists for other sources too), not all fields that are autopopulated from the source are marked with a green background.

**Comment by HebaruSan** [comment]
Specifically, Homepage is populated from GitHub.

(There's an explicit list of which fields are auto-filled per each tab; `resources.homepage` wasn't listed under `github`, and now it is:

https://github.com/KSP-CKAN/metadata-webtool/blob/469f92686e9e93f0bd34229d902a10be55b4a340/refresh_datajs.py#L106-L118
)

**Comment by HebaruSan** [comment]
After some initial fumbling, I think this is fixed now in 469f92686e9e93f0bd34229d902a10be55b4a340. Thanks for spotting this and filing the report.

![image](https://github.com/KSP-CKAN/metadata-webtool/assets/1559108/ed5c2928-11ef-41ec-af30-7291eb7c1969)
